version: '3'
services:
  app:
    build: .
    container_name:  ${APP_NAME}api
    image: ${IMAGE}
    env_file: .env
    command: bash -c "cd /go/src/${REPOSITORY} && go mod tidy && go run ./cmd/api"
    restart: always
    volumes:
      - ./:/go/src/${REPOSITORY}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - mylocal
  db:
    container_name: ${APP_NAME}db
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - ${HOST}:${DB_PORT}:${DB_PORT}
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge